name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Python repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      working-directory: .
      run: |
        RANDOM_HASH=$(openssl rand -hex 4)
        IMAGE_TAG=catprogrammer/downloader_sloniara_bot:$RANDOM_HASH
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Checkout DevOps repository
      uses: actions/checkout@v4
      with:
        repository: catdevdev/fast-devops
        ref: main
        token: ${{ secrets.DEVOPS_REPO_TOKEN }}

    - name: Update Helm chart
      working-directory: ./proxmox-infra/argocd-terraform/envs/dev/argocd-downloader-sloniara-bot/k8s
      run: |
        CHART_PATH="values.yaml"
        sed -i "/^\s*repository:/s|:.*|: catprogrammer/downloader_sloniara_bot|" $CHART_PATH
        sed -i "/^\s*tag:/s|:.*|: ${IMAGE_TAG##*:}|" $CHART_PATH

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add proxmox-infra/dev/argocd/k8s/templates/values.yaml
        git commit -m "Update image to ${{ env.IMAGE_TAG }}"
        git push
