name: Build and deploy

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: downloader-sloniara-bot-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: anomaly51/github-actions-toolkit/.github/workflows/harbor-argocd-app.yml@main
    with:
      app-name: downloader-sloniara-bot
      image-repository: harbor.api-api-api.com/downloader-sloniara-bot/bot
    secrets: inherit
